mainsail-crew/crowsnest

- README.md
Improved readability of device definition section and added text to resolve "Video capture not supported by the device" error when using /dev/video0 on non-RPi hardware.
Signed-off-by: Cor Ruiten <zozo@ruiten.com>
> docs: updated documentation for device definition

- README.md
fix: Typo in readme.md of a folder name in line 244.
The typo is in the directory name `/dev/v4l/by-id`.
Current typos: `v4l`
Expected: `4vl`
> fix: Typo in readme.md of a folder name in line 244.

- README.md
- resources/crowsnest.conf
Tested Orange Pi 4 lts computer using the stock Orangepi4-lts_3.0.6_debian_bullseye_server_linux5.10.43 image and after just using kiauh to do install of klipper/moonraker/mainsail (to current build versions), all worked great out of the box with no changes after stock install per instructions.
> Update README.md (#72)

- libs/v4l2_control.sh
Make it clear that crowsnest uses these two packages instead of how it was written, implying that the packages used crowsnest.
> docs: fix clarity of backend packages

- bin/build.sh
On devices with less than 512MB existing devices will use `-j2` due to wrong condition.
> Fix makefile flags on low memory devices

- bin/build.sh
* Fix `makefile` flags on low memory devices
On devices with less than 512MB existing devices will use `-j2` due to wrong condition.
> Fix makefile flags on low memory devices (#124)

- README.md
This is a follow-up to #108 and fixes heading and hyperlink to the list of backends
> docs: Update index with correct heading and link to backends

- bin/build.sh
- libs/core.sh
'Dependencys' --> dependencies
> Typo in `core.sh`

- bin/build.sh
* Fix `makefile` flags on low memory devices
On devices with less than 512MB existing devices will use `-j2` due to wrong condition.
> Fix makefile flags on low memory devices (#124) (#125)

- tools/libs/pkglist-rpi.sh
`libcamera-apps-lite` is needed for `libcamera-hello`. Crowsnest uses `libcamera-hello` to detected raspicams
> fix: fix libcamera-apps-lite not getting updated

- tools/install.sh
Fixes #141 
The CustomPiOS docker image doesn't have the `SUDO_USER` variable defined during the build process. This PR will skip the sudo privileges check for this specific case
> fix: fix CustomPiOS docker build error

- libs/hwhandler.sh
- libs/logging.sh
If device is a Raspberry Pi and does not have `libcamera-hello`, it does not log devices
Error occurs in Line 93 of logging.sh
> fix(hwhandler.sh): fix error in device logging

- libs/hwhandler.sh
- libs/logging.sh
* fix(hwhandler.sh): fix error in device logging
If device is a Raspberry Pi and does not have libcamera-hello, it does not log devices
Error occurs in Line 93 of logging.sh
* fix: remove unnecessary double funtion calls
> fix(hwhandler.sh): fix error in device logging (#169)

- tools/libs/set_gpumem.sh
On devices with less than 512MB existing devices will use `160` instead of `128` due to wrong condition.
> fix: fix wrong gpumem calculation

- tools/libs/set_gpumem.sh
> Merge develop branch

- bin/build.sh
- tools/configure.sh
- tools/install.sh
- tools/libs/core.sh
Fixes #188 
This will force the main branch of camera-streamer on Bookworm installations.
Therefore it will ignore the branch specified inside `tools/.config` on Bookworm installations.
> fix: add bookworm support

- Makefile
Add `make fixworkingdirectory` to fix the WorkingDirectory path inside the service file to the current working directory.
> chore: add make argument to fix WorkingDirectory

- bin/build.sh
The wrong branch of camera-streamer will be currently cloned with the `--reclone` option of `bin/build.sh` if you are using bookworm.
> fix(build.sh): fix wrong cs branch for cloning

- libs/hwhandler.sh
This will fix issue on Raspberry Pi5, which doesnt generate cam list,
because 'vcgencmd get_camera' exits with an error.
If all conditions fail it will always return '0'
Signed-off-by: Stephan Wendel <me@stephanwe.de>
> fix: fixes error in detect_legacy

- tools/libs/set_gpumem.sh
`do_memory_split` got removed on bookworm. Fixes #219
> fix: skip do_memory_split on bookworm

- libs/ustreamer.sh
- libs/v4l2_control.sh
If one cam with `ustreamer` is defined it will run `brokenfocus` for every cam defined. This will lead to a crash with `brokenfocus` devices with mode `camera-streamer`.
This PR fixes this issue and will only run `brokenfocus` for devices with mode `ustreamer`
> fix: fix crash with brokenfocus and camera-streamer

- bin/build.sh
- tools/libs/build_apps.sh
This reduces the download size and disk usage for `camera-streamer`.
> chore: shallow clone camera-streamer submodules

- bin/build.sh
If one of all the possible backends is not installed, `clean_apps` inside `build.sh` crashes.
> chore: fix `clean_apps` for installations without all backends

- Makefile
`make update` reclones the repositories, so we don't need to clean them before building.
> chore: remove `buildclean` from `make update`

- libs/hwhandler.sh
- libs/logging.sh
This will allow to show more than one "picam" device on raspberry pi5,
till now untested on regular setups but shouldnt interfere with its behaviour as is.
> feat: add dual picam detection

- libs/logging.sh
We currently don't support libcamera devices on the Raspberry Pi 5.
This will add a warning before the libcamera device logging.
> chore: add warning for libcamera on pi5

- libs/core.sh
If ustreamer is not installed, the dependency check will print an empty string because it is not found.
> fix: fix empty string if ustreamer not found

- libs/hwhandler.sh
Fixes small style errors for picam logging:
- Added indentation of camera resolution
- Added indentation for camera controls modes
- Fixed type parsing for camera controls on Bookworm
> fix: fix libcamera resolution and controls logging

- bin/build.sh
- libs/core.sh
- libs/hwhandler.sh
- libs/init_stream.sh
- libs/versioncontrol.sh
- tools/libs/core.sh
Armbian on Raspberry Pi is missing liblivemedia(-dev) and libcamera-apps-lite, so camera-streamer cannot be installed, but starting crowsnest fails due to the missing camera-streamer dependency.
> fix: cs cannot be built on Armbian, so let's not depend on it

- resources/crowsnest.conf
The example crowsnet.conf does not specify what use_proxy is for and it is not immediately obvious. 
The issue is discussed in #34
> docs: improve grammar and style, including capitalization and phrasing

- tools/libs/pkglist-generic.sh
- tools/libs/pkglist-rpi.sh
Ustreamer added pkg-config in v6.13 as dependency. This might not be required to build but is checked in the Makefile.
> fix: fix ustreamer dependencies

- .github/workflows/release.yml
Update git-cliff-action from v2 to v4 and action-gh-release from v1 to v2 in the release action.
This fixes the release action, as git-cliff-action v2 was using a a Buster Docker image.
> chore: update git actions in release.yaml

- bin/build.sh
- tools/dev-helper.sh
The failing functions are used but on different file paths, therefore shellcheck breaks.
We don't know why it suddenly fails. Ignoring it seems like the easiest fix for now.
> ci: fix shellcheck failing
